ZebragonApp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('groups/', include('groups.urls')),
    path('receipts/', include('receipts.urls')),
    path('categories/', include('categories.urls')),
    path('my_messages/', include('my_messages.urls')),
    path('profile_mangement/', include('profile_mangement.urls')),
    path('statistics/', include('statistics_and_plots.urls')),
    path('promotions/', include('promotions_and_discounts.urls')),
    path('', include('shopping_lists.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'users.views.handle404'
handler500 = 'users.views.handle500'

groups/urls.py
from django.urls import path, include
from . import views

app_name = 'groups'
urlpatterns = [
    path('', views.groups, name='groups'),
    path('<int:group_id>/', views.group_site, name='group_site'),
    path('<int:group_id>/invite/', views.invite_page, name='invite_page'),
    path('<int:group_id>/leave_group/', views.leaving_group_page, name='leaving_group_page'),
    path('add_group/', views.add_group, name='add_group'),
    path('<int:group_id>/invite/search/', views.search, name='search'),
    path('<int:group_id>/leave_group/left/', views.left_group, name='left_group'),
    path('<int:group_id>/manage_group/', views.manage_group, name='manage_group'),
    path('<int:group_id>/group_receipts_and_expenses/', views.group_receipts_and_expenses, name='group_receipts_and_expenses'),
    path('search_group/', views.search_group, name='search_group'),
    path('delete_group/<int:group_id>/', views.delete_group, name='delete_group'),
    path('group_deletion/<int:group_id>/', views.group_deletion, name='group_deletion'),
    path('<int:group_id>/password_check/', views.password_check, name='password_check'),
    path('<int:group_id>/change_limit/', views.change_limit, name='change_limit'),
    path('<int:group_id>/change_adding_possibility/', views.change_adding_possibility, name='change_adding_possibility'),
    path('<int:group_id>/not_member_of_group/', views.not_member_of_group, name='not_member_of_group'),
    path('<int:group_id>/change_invite_possibility/', views.change_invite_possibility, name='change_invite_possibility'),
    path('<int:group_id>/remove_member/<int:member_id>/', views.remove_member, name='remove_member'),
    path('<int:group_id>/del_from_group_expenses/<int:expense_id>/', views.del_from_group_expenses, name='del_from_group_expenses'),
    path('<int:group_id>/del_from_group_receipts/<int:receipt_id>/', views.del_from_group_receipts, name='del_from_group_receipts'),
    path('<int:group_id>/del_list_from_group/<int:list_id>/', views.del_list_from_group, name='del_list_from_group'),
    path('<int:group_id>/profile_not_public/', views.profile_not_public, name='profile_not_public'),
    path('<int:group_id>/change_groupcode/', views.change_groupcode, name='change_groupcode'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register')
]

groups/forms.py
from django import forms
from .models import CommonGroups
from django.contrib.auth.models import User
from django.core import validators


class CommonGroupsForm(forms.ModelForm):
    class Meta:
        model = CommonGroups
        fields = ['group_name', 'max_number_of_members','password']
        labels = {'group_name': 'Nazwa grupy',
                  'max_number_of_members': 'Max. liczba członków',
                  'password': 'Hasło',
                 }

        widgets = {
            'group_name': forms.TextInput(attrs={
                'class': "form-control",
                'style': 'width: 300px; margin: auto;border-color: black',
                'placeholder': 'Grupa',
                'label': "Nazwa grupy"
            }),
            'max_number_of_members': forms.NumberInput(attrs={
                'class': "form-control",
                'style': 'width: 300px; margin: auto; border-color: black',
                'max': '50',
                'min': '1',
                'label': "Maksymalna liczba członków"
            }),

            'password': forms.TextInput(attrs={
                'class': "form-control",
                'style': 'width: 300px; margin: auto;border-color: black',
                'label': "Hasło"
            })
        }

    def clean(self):
        # data is feteched using the super function of django
        super(CommonGroupsForm, self).clean()

        group_name = self.cleaned_data.get('group_name')
        max_number_of_members = self.cleaned_data.get('max_number_of_members')
        password = self.cleaned_data.get('password')

        # Nazwa grupy
        if group_name is None:
            self._errors['group_name'] = self.error_class([
                'Nie wpisano nazwy grupy.'
            ])
        elif len(group_name) < 3:
            self._errors['group_name'] = self.error_class([
                'Nazwa musi mieć więcej niż 3 znaki.'
            ])

        # Max liczba członków
        if not isinstance(max_number_of_members,int):
            self._errors['max_number_of_members'] = self.error_class([
                'Należy wprowadzić liczbę od 1 do 50.'
            ])
        else:
            if max_number_of_members < 1:
                self._errors['max_number_of_members'] = self.error_class([
                    'Liczba członków musi być większa od 0.'
                ])
            elif max_number_of_members > 50:
                self._errors['max_number_of_members'] = self.error_class([
                    'Liczba członków musi być mniejsza od 50.'
                ])

        # password
        if password is None:
            self._errors['group_name'] = self.error_class([
                'Nie wpisano hasła.'
            ])
        elif len(password) < 3:
            self._errors['group_name'] = self.error_class([
                'Hasło musi mieć więcej niż 3 znaki.'
            ])

        return self.cleaned_data


class ChangeGroupCodeForm(forms.ModelForm):
    class Meta:
        model = CommonGroups
        fields = ['password']
        labels = {'group_name': 'Nazwa grupy',
                  'max_number_of_members': 'Max. liczba członków',
                  'password': 'Kod dostępu do grupy',
                 }

        widgets = {
            'password': forms.TextInput(attrs={
                'class': "form-control",
                'style': 'width: 300px; margin: auto;border-color: black',
            }),}

groups/views.py
from django.shortcuts import render, redirect
from .models import CommonGroups, User
from groups.forms import CommonGroupsForm, ChangeGroupCodeForm
from django.contrib import messages
from my_messages.models import Message
from profile_mangement.models import ProfileInfo
import math
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.contrib.auth.decorators import login_required


@login_required
def groups(request):
    your_groups = CommonGroups.objects.filter(owner=request.user)
    member_of_groups = CommonGroups.objects.filter(members=request.user).order_by("-date_created")

    page_number = request.GET.get('page',1)
    p = Paginator(member_of_groups, 5)

    try:
        pages = p.page(page_number)
    except PageNotAnInteger:
        pages = p.page(1)
    except EmptyPage:
        pages = p.page(p.num_pages)

    context = {'your_groups': your_groups, "member_of_groups":member_of_groups, 'pages': pages}
    return render(request, 'groups/your_groups.html', context)


import pandas as pd
from receipts.models import Receipt, Expense
from statistics_and_plots.views import calculate_recurrent_expense
import plotly.graph_objects as go


@login_required
def group_site(request, group_id):
    group = CommonGroups.objects.get(id=group_id)
    members = group.members.all().order_by("id")

    profiles = ProfileInfo.objects.filter(user__in=members).order_by("user_id")
    pam = zip(profiles, members)

    page_number = request.GET.get('page', 1)
    p = Paginator(list(pam), 5)

    try:
        pages = p.page(page_number)
    except PageNotAnInteger:
        pages = p.page(1)
    except EmptyPage:
        pages = p.page(p.num_pages)

    user = request.user

    exps = Expense.objects.filter(group=group, is_deleted=False).values_list('amount','owner')
    receipts = Receipt.objects.filter(group=group, is_deleted=False).values_list('amount','owner')

    if exps and receipts:
        df = pd.DataFrame({'owner': list(exps.values_list("owner")) + list(receipts.values_list("owner")),
                           'amount': list(exps.values_list("amount")) + list(receipts.values_list("amount"))})
    elif exps:
        df = pd.DataFrame({'owner': list(exps.values_list("owner")) ,
                           'amount': list(exps.values_list("amount"))})
    elif receipts:
        df = pd.DataFrame({list(receipts.values_list("owner")),
                           list(receipts.values_list("amount"))})

    try:
        df['owner'] = df['owner'].apply(lambda x: x[0])
        df['amount'] = df['amount'].apply(lambda x: x[0])

        users = User.objects.values_list("id", "username")
        df_temp = pd.DataFrame({'owner': users.values_list("id"),
                                'username': users.values_list("username")})
        df_temp['owner'] = df_temp['owner'].apply(lambda x: x[0])
        df_temp['username'] = df_temp['username'].apply(lambda x: x[0])
        df2 = pd.merge(df, df_temp, on=['owner'])
        df2 = df2.sort_values('amount')
        df2 = df2[['username', 'amount']]

        df_rank = df2.copy()
        df2 = df2[['amount', 'username']].groupby('username', as_index=False).sum().sort_values(
                by=['amount'], ascending=False)
        new = df2[:3]
        if len(new) >= 3:
            new.loc[len(new)] = ["Inni", df2['amount'][3:].sum()]
            df2 = new
        if group.limit:
            df2.loc[len(df2)] = ['Pozostało', round(group.limit - float(df2['amount'].sum()), 2)]
        if df2.empty:
            pie_chart = "Brak danych"
        else:
            fig_pie = go.Figure(go.Pie(
                name="",
                hole=0.5,
                values=df2['amount'],
                labels=df2['username'],
                texttemplate="<br>%{value:.2f} zł <br> %{percent} </br>",
                textposition="inside",
            ))
            fig_pie.update_traces(marker=dict(colors=['#4f000b', '#720026', '#ce4257', '#ff7f51','lightgray']))
            fig_pie.update_layout(showlegend=True, margin=dict(t=0, b=0, l=0, r=0),
                                  autosize=False,
                                  height=400,
                                  width=350,
                                  legend=dict(orientation="h"))
            pie_chart = fig_pie.to_html(full_html=False, include_plotlyjs=False)
    except:
        pie_chart= "Brak wykresu."

    if user not in members:
        return redirect('groups:not_member_of_group', group_id=group_id)

    try:
        df_rank = df_rank[['amount', 'username']].groupby('username', as_index=False).sum().sort_values(
            by=['amount'], ascending=False)
        new = df_rank[:3]
        df_rank = new

        if df_rank.empty:
            bars_chart = "Brak danych"
        else:

            fig_bars = go.Figure(data=[
                go.Bar(name='SF Zoo',
                       x=df_rank['username'],
                       y=df_rank['amount'],
                       text=df_rank['amount'],
                       textposition="outside",
                       marker_color=['#4f000b', '#720026', '#ce4257', '#ff7f51'],
                       texttemplate=" %{y:.2} zł", )
            ])
            # marker_color = ["#d4af37", '#c0c0c0', '#cd7f32'],
            fig_bars.update_layout(margin=dict(t=0, b=0, l=0, r=0), height=400,width=350,)

            fig_bars.update_layout(barmode='group')
            bars_chart = fig_bars.to_html(full_html=False, include_plotlyjs=False)

    except:
        bars_chart = "Brak wykresu."

    group_expenses = Expense.objects.filter(group=group_id, is_deleted=False)
    group_receipts = Receipt.objects.filter(group=group_id, is_deleted=False)

    suma_wydatki = 0
    suma_paragony = 0
    if exps:
        df = pd.DataFrame(group_expenses.values_list("expense_name", 'amount', 'group', "date_added", "is_recurrent", "number", "time_stamp"))
        df.columns = ["expense_name", 'amount', 'group', "date_added", "is_recurrent", "number", "time_stamp"]
        df = calculate_recurrent_expense(df)
        suma_wydatki += float(df['amount'].sum())

    for receipt in group_receipts.values_list('amount'):
        suma_paragony += float(receipt[0])

    suma_wydatki = round(float(suma_wydatki), 2)
    suma_paragony = round(float(suma_paragony), 2)
    suma = suma_wydatki + suma_paragony
    amount_per_member = math.ceil(suma/group.number_of_members * 100)/100

    group_sh_list = group.shoppinglist_set.all()
    pg_num = request.GET.get('page', 1)
    ppag = Paginator(group_sh_list, 3)

    try:
        pag = ppag.page(pg_num)
    except PageNotAnInteger:
        pag = ppag.page(1)
    except EmptyPage:
        pag = ppag.page(ppag.num_pages)

    context = {"group": group, "members": members, "user": user, 'amount_per_member': str("{:.2f}".format(amount_per_member)).replace(".", ','),
               "suma": str("{:.2f}".format(suma)).replace(".", ','), "pages": pages, 'pag': pag,
               "pie": pie_chart, "group_sh_list": group_sh_list, 'bars_chart': bars_chart}
    return render(request, 'groups/group_site.html', context)


@login_required
def invite_page(request, group_id):
    group = get_object_or_404(CommonGroups, id=group_id)

    if request.method == 'POST':
            new_message = Message.objects.create(receiver = User.objects.get(username=request.POST["user_to_invite"]),
                                                 sender = request.user, title = "Zaproszenie do grupy " + group.group_name,
                                                 message_type="invitation", group = group
                                                 )
            new_message.text = "Witaj " + new_message.receiver.username + "!\n" + \
                               "Zapraszam Cię do dołączenia do grupy " + group.group_name + "."
            new_message.save()
            messages.success(request, 'Wiadomość została wysłana.')
            return redirect('groups:group_site', group_id=group_id)


    context = {"group": group, "code": group.password}
    return render(request, 'groups/invite_page.html', context)


@login_required
def search(request, group_id):
    text = 'noOne'
    group = get_object_or_404(CommonGroups, id=group_id)
    if request.method == 'POST':
        name = request.POST.get('textfield', None)
        try:
            user = User.objects.get(username=name)

            if group.number_of_members >= group.max_number_of_members:
                text = "Osiągnięto limit członków grupy"
            else:
                text = user
                group.number_of_members = group.number_of_members + 1
                group.members.add(user)
                group.save()

        except User.DoesNotExist:
            text = "Nie ma takiego użytkownika"

    context = {'text': text, 'group': group}
    return render(request, 'groups/search.html', context)


@login_required
def leaving_group_page(request, group_id):
    group = CommonGroups.objects.get(id=group_id)
    if group.members.count() > 1:
        member = group.members.exclude(id=group.owner.id).order_by("date_joined")[0]
    else:
        member = None

    context = {"group": group, "user": request.user, "new_owner": member}
    return render(request, 'groups/leaving_group_page.html', context)


@login_required
def add_group(request):
    if request.method == 'POST':
        form = CommonGroupsForm(request.POST)

        if form.is_valid():
            new_group = form.save(commit=False)
            new_group.owner = request.user
            new_group.save()
            new_group.members.add(request.user)
            messages.success(request, 'Grupa została utworzona')
            return redirect('groups:groups')
    else:
        form = CommonGroupsForm()

    names = list(form._meta.labels.values())
    group_name = names[0]
    max_members = names[1]
    pswd = names[2]

groups/templates/groups/add_group.html
{% extends "shopping_lists/base.html" %}

{% block content %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
        p {
            margin: 30px 30px auto;
        }

        .p_error {
            margin: 0 30px auto;
        }

        .errorlist {
            list-style: none;
            margin: 0 20px auto;
            padding: 0;
            color: red;
            text-align: center;
        }

    </style>

    <a href="{% url 'groups:groups' %}">
        <div style="position: fixed; margin-top: 15px;color: black; margin-left: 15px">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
            </svg>
        </div>
    </a>

    <h2 style="text-align: center; padding-top: 20px">Nowa grupa</h2>

    <div style="margin: 70px auto" >
        <form  novalidate action="{% url 'groups:add_group' %}" method="post">
            {% csrf_token %}
            <p>
                {{ form.group_name.label }}
                {{ form.group_name }}
            </p>
            <p class="p_error">
                {% if form.group_name.errors %}
                    {{ form.group_name.errors }}
                {% else %}
                    &nbsp;
                {% endif %}
            </p>

            <p>
                {{ form.max_number_of_members.label }}
                {{ form.max_number_of_members }}
            </p>
            <p class="p_error">
            {% if form.max_number_of_members.errors %}
                {{ form.max_number_of_members.errors }}
            {% else %}
                 &nbsp;
            {% endif %}
            </p>

            <p>
                {{ form.password.label }}
                {{ form.password }}
            </p>
            <p class="p_error">
                {% if form.password.errors %}
                    {{ form.password.errors }}
                {% else %}
                        &nbsp;
                {% endif %}
            </p>

            <div class="text-center">
                <button style="width: 150px" class="btn btn-dark" name="post_btn">Utwórz</button>
            </div>
        </form>
    </div>

{% endblock content %}

groups/templates/groups/group_deletion.html
{% extends "shopping_lists/base.html" %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <a href="{% url 'groups:manage_group' group.id %}">
        <div style="position: fixed; margin-top: 15px;color: black; margin-left: 15px">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
            </svg>
        </div>
    </a>


    <div style="text-align: center; margin: 30px; padding-top: 50px">
        <svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" fill="currentColor" class="bi bi-exclamation-triangle" viewBox="0 0 16 16">
          <path d="M7.938 2.016A.13.13 0 0 1 8.002 2a.13.13 0 0 1 .063.016.146.146 0 0 1 .054.057l6.857 11.667c.036.06.035.124.002.183a.163.163 0 0 1-.054.06.116.116 0 0 1-.066.017H1.146a.115.115 0 0 1-.066-.017.163.163 0 0 1-.054-.06.176.176 0 0 1 .002-.183L7.884 2.073a.147.147 0 0 1 .054-.057zm1.044-.45a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566z"/>
          <path d="M7.002 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 5.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995z"/>
        </svg>
    </div>

    <h1>Usuwasz grupę!</h1>

    <div style="padding: 10px;margin: 10px">
        <p style="text-align:justify;">Czy na pewno chcesz usunąć grupę?
            <br>
            Wszelkie zgromadzone przez Ciebie dane zostaną nieodwracalnie usunięte!
            Wszyscy członkowie zostaną z niej usunięci, a zgromadzone paragony i wydatki przepadną.
        </p>
        <p style="text-align: center">Czy chcesz kontynuować?</p>
    </div>

    <div style="text-align: center">
    <a id="btn_1" style="margin: 10px; width: 80%;" href="{% url 'groups:manage_group' group.id %}" class="btn btn-dark" >
        Nie, rezygnuję
    </a>
        <a href="{% url 'groups:delete_group' group.id %}" class="btn btn-danger" id="btn_2" style="margin: 10px; width: 80%;">Tak, chcę usunąć grupę</a>
    </div>

{% endblock content %}

groups/templates/groups/leaving_group_page.html
{% extends "shopping_lists/base.html" %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <style>

        .messages{
            color: red;
            margin: 0 auto;
            text-align: center;
        }

    </style>

    <a href="{% url 'groups:group_site' group.id %}">
        <div style="position: fixed; margin-top: 15px;color: black; margin-left: 15px">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
            </svg>
        </div>
    </a>

    <div style="margin: 10px; padding: 10px">
    <h3 style="padding:10px;text-align: center; margin: 80px 10px 10px;">  Opuszczasz grupę {{ group.group_name }}</h3>
    {% if user == group.owner %}
        {% if new_owner != None %}
                        <div style="text-align: center">
                <b>Jesteś założycielem grupy.</b>
            </div>

            <div style="margin: 10px; padding:10px;text-align: justify;">

                    <div>
                    Jeśli ją opuścisz, inna osoba przejmie status właściciela grupy.
                    Możesz wybrać swojego następcę albo właścicielem zostanie osoba będąca członkiem najdłużej.
                    </div>

            </div>


        <form style="margin: 20px" id="form" method="post" action="{% url 'groups:left_group' group.id%}">
            {% csrf_token %}
            <label for="new_owner">Nowy właściciel grupy:</label>
            <br>
            <input class="form-control" placeholder="{{ new_owner }}" id="new_owner" type="text" name="new_owner">

        <div style="height: 20px">
            {% if messages %}
                <div id="messages" class="messages">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
                </div>
            {% endif %}
        </div>
        </form>

            <div style="margin: 10px; padding:10px;text-align: justify">
                Wszelkie dane zebrane przez Ciebie dotychczas w tej grupie zostaną usunięte!
            </div>

            <div style="text-align: center; margin: 40px auto">
                <h5>Czy na pewno chcesz kontynuować?</h5>
                <button style="margin: 10px; width: 100px" class="btn btn-danger" type="submit" form="form">TAK</button>
                <a style="margin: 10px; width: 100px" class="btn btn-black" href="{% url 'groups:group_site' group.id %}">NIE</a>
            </div>

        {% else %}
            <h3 style="padding:10px;text-align: center; margin: 80px 10px 10px;">  Czy na pewno chcesz opuścić grupę {{ group.group_name }}?</h3>
            <div style="text-align: center">
                <b>Jesteś założycielem grupy.</b>
            </div>

            <div style="margin: 10px; padding:10px;text-align: justify;">

                    <div>
                    Jeśli ją opuścisz, grupa zostanie usunięta, gdyż nie będzie możliwe wybranie Twojego następcy.
                    </div>

            </div>

            <div style="margin: 10px; padding:10px;text-align: justify">
                Wszelkie dane zebrane przez Ciebie dotychczas w tej grupie zostaną usunięte!
            </div>

            <div style="text-align: center; margin: 40px auto">
                <h5>Czy na pewno chcesz kontynuować?</h5>
                <a href="{% url 'groups:delete_group' group.id %}" style="margin: 10px; width: 100px" class="btn btn-danger">TAK</a>
                <a style="margin: 10px; width: 100px" class="btn btn-dark" href="{% url 'groups:group_site' group.id %}">NIE</a>
            </div>

        {% endif %}
    {% else %}
        <div style="margin: 10px; padding:10px;text-align: justify">
            Wszelkie dane zebrane przez Ciebie dotychczas w tej grupie zostaną usunięte!
        </div>

        <div style="text-align: center; margin: 40px auto">
            <h5>Czy na pewno chcesz kontynuować?</h5>
            <a href="{% url 'groups:left_group' group.id %}" style="margin: 10px; width: 100px" class="btn btn-danger">TAK</a>
            <a style="margin: 10px; width: 100px" class="btn btn-dark" href="{% url 'groups:group_site' group.id %}">NIE</a>
        </div>
    {% endif %}

    </div>

{% endblock content %}

groups/templates/groups/messages.html
{% extends "shopping_lists/base.html" %}

{% block content %}

    <div style="padding-top: 80px">

    </div>

    <div>
        <h1 style="text-align: center">Twoje wiadomości</h1>
    </div>
{% endblock content %}

groups/templates/groups/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        <p>{{ text }}</p>

</body>
</html>