ZebragonApp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('groups/', include('groups.urls')),
    path('receipts/', include('receipts.urls')),
    path('categories/', include('categories.urls')),
    path('my_messages/', include('my_messages.urls')),
    path('profile_mangement/', include('profile_mangement.urls')),
    path('statistics/', include('statistics_and_plots.urls')),
    path('promotions/', include('promotions_and_discounts.urls')),
    path('', include('shopping_lists.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'users.views.handle404'
handler500 = 'users.views.handle500'

my_messages/urls.py
from django.urls import path, include
from . import views

app_name = 'my_messages'
urlpatterns = [
    path('', views.your_messages, name='your_messages'),
    path('sent/', views.message_sent, name='message_sent'),
    path('member_accepted/<int:message_id>/', views.member_accepted, name='member_accepted'),
    path('member_rejected/<int:message_id>/', views.member_rejected, name='member_rejected'),
    path('membership_accepted/<int:message_id>/', views.membership_accepted, name='membership_accepted'),
    path('membership_rejected/<int:message_id>/', views.membership_rejected, name='membership_rejected'),
    path('new_message/', views.new_message, name='new_message'),
    path('<int:message_id>/', views.message_inside, name='message_inside'),
    path('delete_messages/', views.delete_messages, name='delete_messages'),
    path('del_all_messages/', views.del_all_messages, name='del_all_messages'),
    path('delete_all/', views.delete_all, name='delete_all'),
    path('black_list/', views.black_list, name='black_list'),
    path('unban/<int:user_id>', views.unban, name='unban'),
    path('add_to_blacklist/', views.add_to_blacklist, name='add_to_blacklist'),
    path('block_options/', views.block_options, name='block_options'),
    path('delete_sent_messages/', views.delete_sent_messages, name='delete_sent_messages'),
    path('message_settings/', views.message_settings, name='message_settings'),
    path('answer_message/<int:message_id>/', views.answer_message, name='answer_message'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register')
]

my_messages/models.py
from django.db import models
from django.contrib.auth.models import User
from groups.models import CommonGroups

# Create your models here.


class Message(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sender")
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="receiver")
    new = models.BooleanField(default=True)
    message_type = models.CharField(max_length=200, default="normal")
    group = models.ForeignKey(CommonGroups, on_delete=models.CASCADE, blank=True, null=True)
    is_seen_by_sender = models.BooleanField(default=True)
    is_seen_by_receiver = models.BooleanField(default=True)
    answered = models.BooleanField(default=False)

    def __str__(self):
        if len(self.title) < 20:
            return self.title
        else:
            return self.title[:20] + "..."

my_messages/forms.py
from django import forms
from .models import Message, User


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['receiver']
        labels = {'receiver': 'Odbiorca'}

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user',None)
        self.members = kwargs.pop('members',None)
        super().__init__(*args, **kwargs)

    def clean(self):
        super(MessageForm, self).clean()

        receiver = self.cleaned_data.get('receiver')
        sender = self.user

        # Nazwa grupy
        if receiver is None:
            self._errors['receiver'] = self.error_class([
                'Nie ma takiego użytkownika.'
            ])

        if receiver == sender:
            self._errors['receiver'] = self.error_class([
                'Nie możesz wysłać zaproszenia do samego siebie!'
            ])

        if receiver in self.members.all():
            self._errors['receiver'] = self.error_class([
                'Ta osoba należy już do grupy.'
            ])

        return self.cleaned_data


class NewMessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['receiver', 'text', 'title']
        labels = {'receiver': 'Odbiorca', 'text': "Treść wiadomości", 'title': "Tytuł"}

        widgets = {
            'receiver': forms.TextInput(
                attrs={'class': "form-control",
                       'style': "border-color: black;"}
            ),

            'title': forms.TextInput(
                attrs={'class': "form-control",
                       'style': "border-color: black;"}
            ),

            'text': forms.Textarea(
                attrs={'class': "form-control",
                       'rows': 14,
                       'style': "border-color: black;"}
            ),
        }

    def clean(self):
        super(NewMessageForm, self).clean()
        receiver = self.cleaned_data.get('receiver')
        print(receiver)
        title = self.cleaned_data.get('title')
        text = self.cleaned_data.get('text')

        if not User.objects.filter(username=receiver):
            self._errors['receiver'] = self.error_class([
                'Nie ma takiego użytkownika.'
            ])
            self.data['receiver'] = ''

        if len(text) < 1:
            self._errors['text'] = self.error_class([
                'Nie można wysłać pustej wiadomości.'
            ])

        if len(title) < 1:
            self._errors['title'] = self.error_class([
                'Proszę dodać wtytuł wiadomości.'
            ])
        elif len(title) > 200:
            self._errors['title'] = self.error_class([
                f'Tytuł nie może przekraczać 200 znaków. Aktualna liczba znaków to {len(title)}.'
            ])


class HiddenMessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['receiver']
        labels = {'receiver': 'Odbiorca'}

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user',None)
        self.members = kwargs.pop('members',None)
        super().__init__(*args, **kwargs)

    def clean(self):
        super(HiddenMessageForm, self).clean()

        receiver = self.cleaned_data.get('receiver')
        sender = self.user

        # Nazwa grupy
        if receiver is None:
            self._errors['receiver'] = self.error_class([
                'Nie ma takiego użytkownika.'
            ])

        return self.cleaned_data

my_messages/views.py
from django.shortcuts import render, redirect
from .models import Message, User
from groups.models import CommonGroups
from .forms import NewMessageForm
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.http import Http404
from profile_mangement.models import ProfileInfo


@login_required
def your_messages(request):
    all_messages = Message.objects.filter(receiver=request.user).order_by('-date_created')
    page_number = request.GET.get('page',1)

    for mes in all_messages:
        if not mes.is_seen_by_receiver and not mes.is_seen_by_sender:
            mes.delete()

    new = all_messages.filter(is_seen_by_receiver=True)

    p = Paginator(new, 5)

    try:
        pages = p.page(page_number)
    except PageNotAnInteger:
        pages = p.page(1)
    except EmptyPage:
        pages = p.page(p.num_pages)

    context = {'all_messages': new, 'pages': pages, 'user': request.user}
    return render(request, 'my_messages/messages.html', context)


@login_required
def message_inside(request, message_id):
    message = Message.objects.get(id=message_id)

    if request.user != message.receiver and request.user != message.sender:
        return Http404

    if request.user.username == message.receiver.username or request.user.username == message.sender.username:
        if request.user.username == message.receiver.username:
            message.new = False

        message.save()
        context = {'message': message, 'user': request.user}
        return render(request, 'my_messages/message_inside.html', context)
    else:
        return Http404


@login_required
def message_sent(request):
    all_messages = Message.objects.filter(sender=request.user, group=None).order_by('-date_created')
    page_number = request.GET.get('page',1)

    for mes in all_messages:
        if not mes.is_seen_by_receiver and not mes.is_seen_by_sender:
            mes.delete()

    new = all_messages.filter(is_seen_by_sender=True)

    p = Paginator(new, 5)

    try:
        pages = p.page(page_number)
    except PageNotAnInteger:
        pages = p.page(1)
    except EmptyPage:
        pages = p.page(p.num_pages)



    context = {'all_messages': new, 'pages': pages}
    return render(request, 'my_messages/message_sent.html', context)


@login_required
def new_message(request):
    if request.method == 'POST':
        form_temp = NewMessageForm(data=request.POST)
        req_temp = request.POST.copy()
        filtr = User.objects.filter(username=form_temp.data['receiver'])
        if filtr:
            req_temp.update({'receiver': filtr[0]})
            prof = ProfileInfo.objects.get(user=filtr[0])
            if request.user in prof.blocked_users.all():
                messages.error(request, "Nie można wysłać wiadomości - użytkownik Cię zablokował.")
                form = NewMessageForm(req_temp)
                context = {'form': form, 'user': request.user}
                return render(request, 'my_messages/new_message.html', context)
        else:
            req_temp.update({'receiver': filtr})
        form = NewMessageForm(req_temp)

        if form.is_valid():
            new_mes = form.save(commit=False)
            new_mes.sender = request.user
            new_mes.save()

            messages.success(request, "Wiadomość została wysłana.")
            return redirect('my_messages:your_messages')
        else:
            messages.error(request, "Wystąpił błąd podczas wysyłania wiadomości.")
    else:
        form = NewMessageForm()

    context = {'form': form, 'user': request.user}
    return render(request, 'my_messages/new_message.html', context)


@login_required
def member_accepted(request, message_id):
    message = Message.objects.get(id=message_id)
    group = CommonGroups.objects.get(id=message.group.id)
    profile = ProfileInfo.objects.get(user=message.sender)
    if profile.messages_by_groups:
        if group.number_of_members < group.max_number_of_members and message.sender not in group.members.all():
            group.members.add(message.sender)
            group.number_of_members += 1
            group.save()

            new_message = Message()
            new_message.sender = request.user
            new_message.receiver = message.sender

            new_message.title = "Gratulacje! Dołączyłeś do grupy " + group.group_name
            new_message.text = "Witaj " + new_message.receiver.username + "!\n" + \
                               "Od dzisiaj jesteś członkiem grupy " + group.group_name + "."
            new_message.message_type = "request_accepted"
            new_message.group = group
            new_message.save()

            messages.success(request, 'Wiadomość została wysłana.')
            message.answered = True
            message.save()
            return redirect('my_messages:message_inside', message_id=message.id)
        else:
            messages.error(request, 'Nie można dodać członka!')
            return redirect('my_messages:message_inside', message_id=message.id)
    else:
        messages.error(request, 'Użytkownik zablokował otrzymywanie wiadomości od grup.')
        return redirect('my_messages:message_inside', message_id=message.id)


@login_required
def membership_accepted(request, message_id):
    message = Message.objects.get(id=message_id)
    group = CommonGroups.objects.get(id=message.group.id)
    profile = ProfileInfo.objects.get(user=message.sender)
    if profile.messages_by_groups:
        if group.number_of_members < group.max_number_of_members and message.receiver not in group.members.all():
            group.members.add(message.sender)
            group.number_of_members += 1
            group.save()
            new_message = Message()
            new_message.sender = request.user
            new_message.receiver = message.sender

            new_message.title = "Użytkownik " + request.user + " dołączył do Twojej grupy " + group.group_name + "!"
            new_message.text = "Witaj " + new_message.receiver.username + "!\n" + \
                               "Użytkownik " + request.user + " dołączył do Twojej grupy  " + group.group_name + "."
            new_message.message_type = "membership_accepted"
            new_message.group = group
            new_message.save()

            messages.success(request, 'Wiadomość została wysłana.')
            message.answered = True
            message.save()

            return redirect('my_messages:message_inside', message_id=message.id)
        else:
            messages.error(request, 'Nie można dołączyć z powodu braku miejsca w grupie! '
                                    'Skontaktuj się z właścicielem grupy w celu wyjaśnienia sytuacji.')
            return redirect('my_messages:message_inside', message_id=message.id)
    else:
        messages.error(request, 'Użytkownik zablokował otrzymywanie wiadomości od grup.')
        return redirect('my_messages:message_inside', message_id=message.id)


@login_required
def member_rejected(request, message_id):
    message = Message.objects.get(id=message_id)
    group = CommonGroups.objects.get(id=message.group.id)
    profile = ProfileInfo.objects.get(user=message.sender)
    if profile.messages_by_groups:
        new_message = Message()
        new_message.sender = request.user
        new_message.receiver = message.sender

        new_message.title = "Prośba o dołączenie do grupy " + group.group_name + " została odrzucona."
        new_message.text = "Witaj " + new_message.receiver.username + "!\n" + \
                           "Niestety, Twoja prośna o przyjęcie do grupy " + group.group_name + " została odrzucona przez jej właściciela."
        new_message.message_type = "request_rejected"
        new_message.group = group
        new_message.save()

        messages.success(request, 'Wiadomość została wysłana.')
        message.answered = True
        message.save()

        return redirect('my_messages:your_messages')
    else:
        messages.error(request, 'Użytkownik zablokował otrzymywanie wiadomości od grup.')
        return redirect('my_messages:your_messages')


@login_required
def membership_rejected(request, message_id):
    message = Message.objects.get(id=message_id)
    group = CommonGroups.objects.get(id=message.group.id)
    profile = ProfileInfo.objects.get(user=message.sender)
    if profile.messages_by_groups:
        new_message = Message()
        new_message.sender = request.user
        new_message.receiver = message.sender

        new_message.title = "Użytkownik " + request.user.username + " odrzucił zaproszenie do grupy " + group.group_name
        new_message.text = "Witaj " + new_message.receiver.username + "!\n" + \
                           "Niestety, użytkownik, którego zaprosiłeś do grupy " + group.group_name + " odrzucił Twoje zaproszenie."
        new_message.message_type = "membership_rejected"
        new_message.group = group
        new_message.save()

        messages.success(request, 'Wiadomość została wysłana.')
        message.answered = True
        message.save()

        return redirect('my_messages:your_messages')
    else:
        messages.error(request, 'Użytkownik zablokował otrzymywanie wiadomości od grup.')
        return redirect('my_messages:your_messages')

@login_required
def delete_messages(request):
    if request.method == 'POST':
        keys = list(request.POST.keys())[1:]
        for key_id in keys:
            mes = Message.objects.get(id=int(key_id))
            if request.user == mes.sender:
                mes.is_seen_by_sender = False
            elif request.user == mes.receiver:
                mes.is_seen_by_receiver = False
            mes.save()
            messages.success(request, "Usunięto wiadomości")
        return redirect("my_messages:your_messages")


@login_required
def delete_sent_messages(request):
    if request.method == 'POST':

my_messages/templates/my_messages/message_inside.html
{% extends "shopping_lists/base.html" %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>


    {% if message.sender == user %}
        <a href="{% url 'my_messages:message_sent' %}">
    {% else %}
        <a href="{% url 'my_messages:your_messages' %}">
    {% endif %}

        <div style="position: absolute; margin-top: 15px;color: black; margin-left: 15px">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
            </svg>
        </div>
    </a>

    <div>
        <h2 style="margin: 10px auto;padding-top: 70px; max-width: 400px; word-wrap: anywhere; text-align: center">{{ message.title }}</h2>
    </div>

    <div style="padding: 10px; min-width: 400px; max-width: 500px; margin: 10px auto; border: 1px solid black; border-radius: 10px">
        <b>Data wysłania:</b>
        {{ message.date_created|date:'H:i, d.m.Y '}}
        <br>
        <b>Nadawca:</b> {{ message.sender }}
        <br>
        <b>Odbiorca:</b> {{ message.receiver }}
    </div>

    <div style="min-height: 400px;min-width: 400px; max-width: 500px; padding: 10px; margin: 10px auto; background-color: rgba(183,183,183,0.26); border-radius: 5px;border-color: black;
    border-style: solid; border-width: 1px">
        {{ message.text|linebreaks }}
    </div>

    <div style="text-align: center;">
        {% if message.group %}
            {% if not message.answered %}
                {% if message.message_type == "invitation" %}
                    <a class="btn btn-success" style="margin:10px; width: 120px" href="{% url 'my_messages:membership_accepted' message.id %}">Dołącz do grupy!</a>
                    <a class="btn btn-danger" style="margin:10px; width: 120px" href="{% url 'my_messages:membership_rejected' message.id %}">Odrzuć</a>
                {% elif message.message_type == "request" %}
                    <a class="btn btn-success" style="margin:10px; width: 120px" href="{% url 'my_messages:member_accepted' message.id %}">Zaakceptuj</a>
                    <a class="btn btn-danger" style="margin:10px; width: 120px"  href="{% url 'my_messages:member_rejected' message.id %}">Odrzuć</a>
                {% endif %}
            {% else %}
                <b style="margin:10px; text-align: center">Już odpowiedziano na tę wiadomość</b>
            {% endif %}

        {% elif message.message_type == "normal" %}
            {% if user == message.receiver %}
                <a class="btn btn-dark" style="margin:10px; width: 120px" href="{% url 'my_messages:answer_message' message.id %}">Odpowiedz</a>
            {% endif %}
            {% elif message.message_type == "info" %}

        {% endif %}
    </div>


{% endblock content %}

my_messages/templates/my_messages/message_settings.html
{% extends "shopping_lists/base.html" %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                     <div id="messages" class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% else %}
                     <div id="messages" class="alert alert-danger">
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}

        <script>
            var mess = document.getElementById("messages")

            setTimeout(function(){
                mess.style.display="none";
            },2000)
        </script>

    <a href="{% url 'my_messages:your_messages' %}">
        <div style="position: absolute; margin-top: 15px;color: black; margin-left: 15px">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
            </svg>
        </div>
    </a>

    <h1 style="text-align: center; margin: 20px">Ustawienia</h1>

    <div style="margin: 10px auto; padding: 10px; display: inline-block; vertical-align: middle; max-width: 600px">
        <h3 style="font-weight:1000;">Czarna lista</h3>
        <div>
            <div style="text-align: justify">
                Na czarnej liście znajdują się gracze, od których nie chcesz
                otrzymywać wiadomości. W każdym momencie możesz dodać lub usunąć danego gracz.
            </div>
            <p style="margin: 10px 0 10px 0">
                <i>
                    {% if blocked_number > 0 %}
                        Masz <b>{{ blocked_number }}</b> zablokowanych użytkowników na liście.
                    {% else %}
                        Nie dodałeś jeszcze żadnego użytkownika do listy.
                    {% endif %}
                </i>
            </p>

            <br>
            <div style="text-align: center">
                <a href="{% url 'my_messages:black_list' %}" class="btn btn-dark" style="width: 200px">
                    <svg xmlns="http://www.w3.org/2000/svg" style="margin-right: 10px; display: inline-block; vertical-align: middle" width="24" height="24" fill="currentColor" class="bi bi-person-fill-slash" viewBox="0 0 16 16">
                      <path d="M13.879 10.414a2.501 2.501 0 0 0-3.465 3.465l3.465-3.465Zm.707.707-3.465 3.465a2.501 2.501 0 0 0 3.465-3.465Zm-4.56-1.096a3.5 3.5 0 1 1 4.949 4.95 3.5 3.5 0 0 1-4.95-4.95ZM11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm-9 8c0 1 1 1 1 1h5.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.544-3.393C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4Z"/>
                    </svg>
                    <div style="display: inline; vertical-align: middle">
                        Zarządzaj listą
                    </div>
                </a>
            </div>
        </div>
    </div>

    <div style="margin: 10px auto 0 auto; padding: 10px; display: inline-block; vertical-align: middle; max-width: 600px">
        <h3 style="font-weight:1000;">Blokowanie</h3>
        <div>
            <div style="text-align: justify">
                Możesz zablokować możliwość wysyłania wiadomości przez grupy, użytkowników lub
                całkowicie wyłączyć możliwość otrzymywania wiadomości. Blokuj wiadomości od:
            </div>


            <form id="form" method="post" action="{% url 'my_messages:block_options' %}">
                {% csrf_token %}
                <div style="margin: 10px">
                    <div class="form-check">
                        {% if profile.messages_by_groups and profile.messages_by_users %}
                            <input class="form-check-input" type="radio" name="block_radio" id="black_list" value="black_list" checked>
                        {% else %}
                            <input class="form-check-input" type="radio" name="block_radio" id="black_list" value="black_list">
                        {% endif %}
                      <label class="form-check-label" for="black_list">
                        Osób z czarnej listy
                      </label>
                    </div>

                    <div class="form-check">
                        {% if profile.messages_by_groups and not profile.messages_by_users %}
                            <input class="form-check-input" type="radio" name="block_radio" id="users" value="users" checked>
                        {% else %}
                            <input class="form-check-input" type="radio" name="block_radio" id="users" value="users">
                        {% endif %}
                      <label class="form-check-label" for="users">
                        Wszystkich użytkowników
                      </label>
                    </div>

                    <div class="form-check">
                        {% if not profile.messages_by_groups and profile.messages_by_users %}
                            <input class="form-check-input" type="radio" name="block_radio" id="groups" value="groups" checked>
                        {% else %}
                            <input class="form-check-input" type="radio" name="block_radio" id="groups" value="groups">
                        {% endif %}
                      <label class="form-check-label" for="groups">
                        Wszystkich grup
                      </label>
                    </div>

                    <div class="form-check">
                        {% if not profile.messages_by_groups and not profile.messages_by_users %}
                            <input class="form-check-input" type="radio" name="block_radio" id="groups_users" value="groups_users" checked>
                        {% else %}
                            <input class="form-check-input" type="radio" name="block_radio" id="groups_users" value="groups_users">
                        {% endif %}
                      <label class="form-check-label" for="groups_users">
                        Wszystkich
                      </label>
                    </div>
                </div>

                <div style="text-align: center">
                    <button class="btn btn-dark" style="width: 200px; margin-top: 10px" type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" style="margin-right: 10px; display: inline-block; vertical-align: middle" width="24" height="24" fill="currentColor" class="bi bi-send-slash" viewBox="0 0 16 16">
                          <path d="M15.964.686a.5.5 0 0 0-.65-.65L.767 5.855a.75.75 0 0 0-.124 1.329l4.995 3.178 1.531 2.406a.5.5 0 0 0 .844-.536L6.637 10.07l7.494-7.494-1.895 4.738a.5.5 0 1 0 .928.372l2.8-7Zm-2.54 1.183L5.93 9.363 1.591 6.602l11.833-4.733Z"/>
                          <path d="M14.975 10.025a3.5 3.5 0 1 0-4.95 4.95 3.5 3.5 0 0 0 4.95-4.95Zm-4.243.707a2.501 2.501 0 0 1 3.147-.318l-3.465 3.465a2.501 2.501 0 0 1 .318-3.147Zm.39 3.854 3.464-3.465a2.501 2.501 0 0 1-3.465 3.465Z"/>
                        </svg>
                        <div style="display: inline; vertical-align: middle">
                            Zmień
                        </div>
                    </button>
                </div>

            </form>

        </div>
    </div>

    <div style="margin: 10px auto; padding: 10px; display: inline-block; vertical-align: middle; max-width: 600px">
        <h3 style="font-weight:1000;">Usuń wiadomości</h3>
        <div>
            <div style="text-align: justify">
                W tym miejscu możesz opróżnić swoją skrzynkę pocztową. Operacja ta sprawi, że
                wszystkie <b>wiadomości odebrane i wysłane zostaną usunięte bezpowrotnie!</b>
            </div>

            <br>
            <div style="text-align: center">
                <a href="{% url 'my_messages:del_all_messages' %}" class="btn btn-danger" style="width: 200px">
                    <svg xmlns="http://www.w3.org/2000/svg" style="margin-right: 10px; display: inline-block; vertical-align: middle" width="24" height="24"  fill="currentColor" class="bi bi-envelope-x" viewBox="0 0 16 16">
                      <path d="M2 2a2 2 0 0 0-2 2v8.01A2 2 0 0 0 2 14h5.5a.5.5 0 0 0 0-1H2a1 1 0 0 1-.966-.741l5.64-3.471L8 9.583l7-4.2V8.5a.5.5 0 0 0 1 0V4a2 2 0 0 0-2-2H2Zm3.708 6.208L1 11.105V5.383l4.708 2.825ZM1 4.217V4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v.217l-7 4.2-7-4.2Z"/>
                      <path d="M16 12.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Zm-4.854-1.354a.5.5 0 0 0 0 .708l.647.646-.647.646a.5.5 0 0 0 .708.708l.646-.647.646.647a.5.5 0 0 0 .708-.708l-.647-.646.647-.646a.5.5 0 0 0-.708-.708l-.646.647-.646-.647a.5.5 0 0 0-.708 0Z"/>
                    </svg>
                    <div style="display: inline; vertical-align: middle">
                        Opróżnij skrzynkę
                    </div>
                </a>
            </div>
        </div>
    </div>

{% endblock content %}