ZebragonApp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('groups/', include('groups.urls')),
    path('receipts/', include('receipts.urls')),
    path('categories/', include('categories.urls')),
    path('my_messages/', include('my_messages.urls')),
    path('profile_mangement/', include('profile_mangement.urls')),
    path('statistics/', include('statistics_and_plots.urls')),
    path('promotions/', include('promotions_and_discounts.urls')),
    path('', include('shopping_lists.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'users.views.handle404'
handler500 = 'users.views.handle500'

groups/urls.py
from django.urls import path, include
from . import views

app_name = 'groups'
urlpatterns = [
    path('', views.groups, name='groups'),
    path('<int:group_id>/', views.group_site, name='group_site'),
    path('<int:group_id>/invite/', views.invite_page, name='invite_page'),
    path('<int:group_id>/leave_group/', views.leaving_group_page, name='leaving_group_page'),
    path('add_group/', views.add_group, name='add_group'),
    path('<int:group_id>/invite/search/', views.search, name='search'),
    path('<int:group_id>/leave_group/left/', views.left_group, name='left_group'),
    path('<int:group_id>/manage_group/', views.manage_group, name='manage_group'),
    path('<int:group_id>/group_receipts_and_expenses/', views.group_receipts_and_expenses, name='group_receipts_and_expenses'),
    path('search_group/', views.search_group, name='search_group'),
    path('delete_group/<int:group_id>/', views.delete_group, name='delete_group'),
    path('group_deletion/<int:group_id>/', views.group_deletion, name='group_deletion'),
    path('<int:group_id>/password_check/', views.password_check, name='password_check'),
    path('<int:group_id>/change_limit/', views.change_limit, name='change_limit'),
    path('<int:group_id>/change_adding_possibility/', views.change_adding_possibility, name='change_adding_possibility'),
    path('<int:group_id>/not_member_of_group/', views.not_member_of_group, name='not_member_of_group'),
    path('<int:group_id>/change_invite_possibility/', views.change_invite_possibility, name='change_invite_possibility'),
    path('<int:group_id>/remove_member/<int:member_id>/', views.remove_member, name='remove_member'),
    path('<int:group_id>/del_from_group_expenses/<int:expense_id>/', views.del_from_group_expenses, name='del_from_group_expenses'),
    path('<int:group_id>/del_from_group_receipts/<int:receipt_id>/', views.del_from_group_receipts, name='del_from_group_receipts'),
    path('<int:group_id>/del_list_from_group/<int:list_id>/', views.del_list_from_group, name='del_list_from_group'),
    path('<int:group_id>/profile_not_public/', views.profile_not_public, name='profile_not_public'),
    path('<int:group_id>/change_groupcode/', views.change_groupcode, name='change_groupcode'),
]

receipts/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'receipts'
urlpatterns = [
    path('', views.your_receipts, name='your_receipts'),
    path('guarantees/', views.guarantees, name='guarantees'),
    path('new_receipt/', views.new_receipt, name='new_receipt'),
    path('new_receipt_group/<int:group_id>', views.new_receipt_group, name='new_receipt_group'),
    path('new_receipt_mainpage/', views.new_receipt_mainpage, name='new_receipt_mainpage'),
    path('new_guarantee/', views.new_guarantee, name='new_guarantee'),
    path('new_guarantee_from_mainpage/', views.new_guarantee_from_mainpage, name='new_guarantee_from_mainpage'),
    path('costs_by_hand/', views.costs_by_hand, name='costs_by_hand'),
    path('receipt_site/<int:receipt_id>', views.receipt_site, name='receipt_site'),
    path('guarantee_site/<int:guarantee_id>', views.guarantee_site, name='guarantee_site'),
    path('expense_site/<int:expense_id>', views.expense_site, name='expense_site'),
    path('expenses_page/', views.expenses_page, name='expenses_page'),
    path('receipt_by_hand/', views.receipt_by_hand, name='receipt_by_hand'),
    path('receipt_by_hand_mainpage/', views.receipt_by_hand_mainpage, name='receipt_by_hand_mainpage'),
    path('<int:group_id>/receipt_by_hand_group/', views.receipt_by_hand_group, name='receipt_by_hand_group'),
    path('receipts_page/', views.receipts_page, name='receipts_page'),
    path('receipt_settings/', views.receipt_settings, name='receipt_settings'),
    path('expense_settings/', views.expense_settings, name='expense_settings'),
    path('guarantee_settings/', views.guarantee_settings, name='guarantee_settings'),
    path('<int:expense_id>/edit_expense/', views.edit_expense, name='edit_expense'),
    path('<int:expense_id>/<int:group_id>/edit_expense_group/', views.edit_expense_group, name='edit_expense_group'),
    path('<int:expense_id>/edit_expense_mainpage/', views.edit_expense_mainpage, name='edit_expense_mainpage'),
    path('<int:guarantee_id>/edit_guarantee/', views.edit_guarantee, name='edit_guarantee'),
    path('<int:guarantee_id>/edit_guarantee_mainpage/', views.edit_guarantee_mainpage, name='edit_guarantee_mainpage'),
    path('<int:guarantee_id>/elongate_guarantee/', views.elongate_guarantee, name='elongate_guarantee'),
    path('<int:guarantee_id>/elongate_guarantee_mainpage/', views.elongate_guarantee_mainpage, name='elongate_guarantee_mainpage'),
    path('<int:receipt_id>/edit_receipt/', views.edit_receipt, name='edit_receipt'),
    path('<int:receipt_id>/edit_receipt_mainpage/', views.edit_receipt_mainpage, name='edit_receipt_mainpage'),
    path('<int:receipt_id>/<int:group_id>/edit_receipt_group/', views.edit_receipt_group, name='edit_receipt_group'),
    path('<int:receipt_id>/delete_receipt/', views.delete_receipt, name='delete_receipt'),
    path('<int:receipt_id>/<int:group_id>/delete_receipt_group/', views.delete_receipt_group, name='delete_receipt_group'),
    path('<int:receipt_id>/delete_receipt_mainpage/', views.delete_receipt_mainpage, name='delete_receipt_mainpage'),
    path('<int:expense_id>/delete_expense/', views.delete_expense, name='delete_expense'),
    path('<int:expense_id>/<int:group_id>/delete_expense_group/', views.delete_expense_group, name='delete_expense_group'),
    path('<int:expense_id>/delete_expense_mainpage/', views.delete_expense_mainpage, name='delete_expense_mainpage'),
    path('<int:group_id>/add_expense_from_grouppage/', views.add_expense_from_grouppage, name='add_expense_from_grouppage'),
    path('add_expense_from_mainpage/', views.add_expense_from_mainpage, name='add_expense_from_mainpage'),
    path('<int:guarantee_id>/delete_guarantee/', views.delete_guarantee, name='delete_guarantee'),
    path('<int:guarantee_id>/delete_guarantee_mainpage/', views.delete_guarantee_mainpage, name='delete_guarantee_mainpage'),
    path('<int:receipt_id>/OCR_site/', views.OCR_site, name='OCR_site'),
    path('<int:receipt_id>/OCR_site_mainpage/', views.OCR_site_mainpage, name='OCR_site_mainpage'),
    path('<int:receipt_id>/<int:group_id>/OCR_site_group/', views.OCR_site_group, name='OCR_site_group'),
    path('<int:receipt_id>/change_receipt_starred_status/', views.change_receipt_starred_status, name='change_receipt_starred_status'),
    path('<int:receipt_id>/change_receipt_starred_status_mainpage/', views.change_receipt_starred_status_mainpage, name='change_receipt_starred_status_mainpage'),
    path('<int:receipt_id>/<int:group_id>/change_receipt_starred_status_group/', views.change_receipt_starred_status_group, name='change_receipt_starred_status_group'),
    path('<int:expense_id>/change_expense_starred_status/', views.change_expense_starred_status, name='change_expense_starred_status'),
    path('<int:expense_id>/<int:group_id>/change_expense_starred_status_fromgroup/', views.change_expense_starred_status_fromgroup, name='change_expense_starred_status_fromgroup'),
    path('<int:expense_id>/change_expense_starred_status_mainpage/', views.change_expense_starred_status_mainpage, name='change_expense_starred_status_mainpage'),
    path('<int:receipt_id>/receipt_data_read/', views.receipt_data_read, name='receipt_data_read'),
    path('<int:receipt_id>/receipt_site_from_mainpage/', views.receipt_site_from_mainpage, name='receipt_site_from_mainpage'),
    path('<int:receipt_id>/<int:group_id>/receipt_site_from_grouppage/', views.receipt_site_from_grouppage, name='receipt_site_from_grouppage'),
    path('<int:expense_id>/expense_site_from_mainpage/', views.expense_site_from_mainpage, name='expense_site_from_mainpage'),
    path('<int:expense_id>/<int:group_id>/expense_site_from_grouppage/', views.expense_site_from_grouppage, name='expense_site_from_grouppage'),
    path('<int:guarantee_id>/guarantee_site_from_mainpage/', views.guarantee_site_from_mainpage, name='guarantee_site_from_mainpage'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register')
]

receipts/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from categories.models import BaseCategories
from groups.models import CommonGroups
from categories.models import Product
from django.core.validators import MinValueValidator
from promotions_and_discounts.models import Shop

# Create your models here.

TIME_STAMP_CHOICES = (
    ("DNI", "Dni"),
    ("MIESIĘCY", "Miesięcy"),
    ("LAT", "Lat"),
)


class ListProduct(models.Model):
    product_name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    description = models.TextField(max_length=400, blank=True, null=True)

    class Meta:
        verbose_name_plural = 'list products'

    def __str__(self):
        return self.product_name


class Receipt(models.Model):
    receipt_name = models.CharField(default='Nowy paragon',max_length=200)
    receipt_img = models.FileField(upload_to='images/', null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    date_of_receipt_bought = models.DateField(default=datetime.datetime.now, null=True, blank=True)
    amount = models.DecimalField(default=0.00, decimal_places=2, max_digits=20, validators=[MinValueValidator(0.00)], blank=True, null=True)
    receipt_info = models.TextField(default="", null=True, blank=True)
    receipt_text_read_by_OCR = models.TextField(default="", null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(CommonGroups, on_delete=models.CASCADE, blank=True, null=True)
    receipt_categories = models.ManyToManyField(BaseCategories, related_name='receipt_categories',blank=True)
    products = models.ManyToManyField(Product,blank=True)
    is_starred = models.BooleanField(default=False)
    shop = models.ForeignKey(Shop, blank=True,null=True, on_delete=models.SET_NULL)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.receipt_name


class Expense(models.Model):
    expense_name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    is_recurrent = models.BooleanField(default=False)
    amount = models.DecimalField(default=0.00, decimal_places=2, max_digits=20, validators=[MinValueValidator(0.00)])
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(BaseCategories, on_delete=models.CASCADE)
    group = models.ForeignKey(CommonGroups, on_delete=models.CASCADE, blank=True, null=True)
    number = models.PositiveIntegerField(blank=True, null=True)
    time_stamp = models.CharField(max_length=12, choices=TIME_STAMP_CHOICES,default="MIESIĘCY", blank=True, null=True)
    shop = models.ForeignKey(Shop, blank=True, null=True, on_delete=models.SET_NULL)
    is_starred = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.expense_name


class Guarantee(models.Model):
    guarantee_name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    end_date = models.DateField(default=datetime.datetime.now)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    regards = models.TextField(blank=True, null=True)
    receipt = models.ForeignKey(Receipt, on_delete=models.CASCADE, blank=True, null=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.guarantee_name

receipts/templates/receipts/expense_site.html
{% extends "shopping_lists/base.html" %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    {% if flag == "mainpage" %}
        <a href="{% url 'receipts:your_receipts' %}">
    {% elif flag == "group" %}
        <a href="{% url 'groups:group_receipts_and_expenses' group.id %}">
    {% else %}
        <a href="{% url 'receipts:expenses_page' %}">
    {% endif %}

        <div style="position: fixed; margin-top: 15px;color: black; margin-left: 15px">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
            </svg>
        </div>
    </a>
    {% if expense.owner == user %}
    {% if expense.is_starred %}
        <div style="position: absolute; right: 20px; top: 100px">
        {% if flag == "group" %}
            <a style="text-decoration: none; color: goldenrod" href="{% url 'receipts:change_expense_starred_status_fromgroup' expense.id group.id %}">
        {% elif flag == "mainpage" %}
            <a style="text-decoration: none; color: goldenrod" href="{% url 'receipts:change_expense_starred_status_mainpage' expense.id %}">
        {% else %}
            <a style="text-decoration: none; color: goldenrod" href="{% url 'receipts:change_expense_starred_status' expense.id %}">
        {% endif %}

                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                  <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                </svg>
            </a>
        </div>
    {% else %}
        <div style="position: absolute; right: 20px; top: 100px">
        {% if flag == "group" %}
            <a style="text-decoration: none; color: goldenrod"  href="{% url 'receipts:change_expense_starred_status_fromgroup' expense.id group.id %}">
        {% elif flag == "mainpage" %}
            <a style="text-decoration: none; color: goldenrod"  href="{% url 'receipts:change_expense_starred_status_mainpage' expense.id %}">
        {% else %}
            <a style="text-decoration: none; color: goldenrod"  href="{% url 'receipts:change_expense_starred_status' expense.id %}">
        {% endif %}

                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
                  <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
                </svg>
            </a>
        </div>
    {% endif %}
    {% endif %}


    <h1 style="text-align: center; margin-top: 20px">{{ expense.expense_name }}</h1>

    <div style="margin: 10px; padding: 10px">

    <div style="margin:10px; padding: 10px; max-width: 500px; text-align: justify ">
        <h5>Dane ogólne</h5>
        Właściciel: <b>{{ expense.owner }}</b><br>
        Data dodania: <b>{{ expense.date_added|date:"d.m.Y" }}</b><br>
        Suma ogólna: <b>{{ expense.amount }} zł</b><br>
        Należy do grupy:
        <b>
        {% if expense.group %}
            {{ expense.group }}
        {% else %}
            Nie
        {% endif %}
        </b>
    </div>

    <div style="margin:10px; padding: 10px; max-width: 500px; text-align: justify ">
        <h5 style="margin: 0 10px 20px 0">Kategoria wydatku</h5>
        <span style=" margin: 10px; padding: 5px 10px; background-color: {{ expense.category.color }}; max-width: 20px; max-height: 20px; border-radius: 10px">
            &nbsp;
        </span>
        {{ expense.category }}
    </div>

    <div style="margin:10px; padding: 10px; max-width: 500px; text-align: justify ">
        <h5>Powtarzalność</h5>
        {% if expense.is_recurrent %}
            Powtarzalny co <b>{{ expense.number }} {{ expense.time_stamp }}</b>
            {% else %}
            Jednorazowy
        {% endif %}

    </div>
    </div>

    <div style="text-align: center">
        {% if expense.owner == user %}
            <div id="icons_container_id" style="margin: 10px auto;">
            {% if flag == "group" %}
                <a href="{% url 'receipts:edit_expense_group' expense.id group.id %}" style="text-decoration: none; color: black;margin-right: 25px">
            {% elif flag == "mainpage" %}
                <a href="{% url 'receipts:edit_expense_mainpage' expense.id %}" style="text-decoration: none; color: black;margin-right: 25px">
            {% else %}
                <a href="{% url 'receipts:edit_expense' expense.id %}" style="text-decoration: none; color: black;margin-right: 25px">
            {% endif %}
                    <div style="display: inline">
                        <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                          <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                          <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                        </svg>
                    </div>
                    <span style="margin-left: 10px">Edytuj opłatę</span>
                </a>
            </div>

            <div id="icons_container_id" style="margin: 10px auto">
            {% if flag == "group" %}
                <a href="{% url 'receipts:delete_expense_group' expense.id group.id %}" style="text-decoration: none; color: black;margin-right: 35px">
            {% elif flag == "mainpage" %}
                <a href="{% url 'receipts:delete_expense_mainpage' expense.id %}" style="text-decoration: none; color: black;margin-right: 35px">
            {% else %}
                <a href="{% url 'receipts:delete_expense' expense.id %}" style="text-decoration: none; color: black;margin-right: 35px">
            {% endif %}
                        <div style="display: inline; ">
                        <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                          <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                        </svg>
                    </div>
                    <span style="margin-left: 10px">Usuń opłatę</span>
                </a>
            </div>
        {% endif %}
    </div>

{% endblock content %}

receipts/templates/receipts/receipt_by_hand.html
{% extends "shopping_lists/base.html" %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    {% if flag == "mainpage" %}
        <a href="{% url 'receipts:your_receipts' %}">
    {% elif flag == "group" %}
        <a href="{% url 'groups:group_receipts_and_expenses' group %}">
    {% else %}
        <a href="{% url 'receipts:receipts_page' %}">
    {% endif %}
        <div style="position: fixed; margin-top: 15px;color: black; margin-left: 15px">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
            </svg>
        </div>
    </a>

    <h1 style="text-align: center; margin-top: 20px">Nowy paragon</h1>


    <form style="margin: 20px auto;padding: 10px"  enctype="multipart/form-data" method="post" action="{% url 'receipts:receipt_by_hand' %}">
        {% csrf_token %}
        <div style="margin: auto">
            {{ form.receipt_name.label }}
            {{ form.receipt_name }}
        </div>
        <div style="margin: auto">
            {{ form.receipt_img.label }}
            {{ form.receipt_img }}
        </div>
        <div style="margin: auto">
            {{ form.amount.label }}
            {{ form.amount }}
        </div>
        <div style="margin: auto">
            {{ form.receipt_info.label }}
            {{ form.receipt_info }}
        </div>
            {% if flag != "group" %}
                <div style="margin: auto">
                    {{ form.group.label }}
                    {{ form.group }}
                </div>
            {% endif %}
        <div style="margin: auto">
            {{ form.products.label }}
            {{ form.products }}
        </div>
        <div style="margin: auto">
            {{ form.shop.label }}
            {{ form.shop }}
        </div>

        {% if flag == "mainpage" %}
            <input type="hidden" name="flag" value="mainpage">
        {% elif flag == "group" %}
            <input type="hidden" name="flag" value="group">
            <input type="hidden" name="grp" value={{ group }}>
        {% endif %}

        <div style="text-align: center; ">
            <button style="min-width: 150px; margin: 20px" type="submit" class="btn btn-dark">Utwórz</button>
        </div>
    </form>


{% endblock content %}

receipts/templates/receipts/receipt_data_read.html
{% extends "shopping_lists/base.html" %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

<h1>
    Odczytane dane
</h1>

    <p>
        Nazwa: {{ receipt.receipt_name }}
        Suma: {{ receipt.amount }}

        Tekst: {{ receipt.products}}
    </p>


{% endblock content %}