ZebragonApp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('groups/', include('groups.urls')),
    path('receipts/', include('receipts.urls')),
    path('categories/', include('categories.urls')),
    path('my_messages/', include('my_messages.urls')),
    path('profile_mangement/', include('profile_mangement.urls')),
    path('statistics/', include('statistics_and_plots.urls')),
    path('promotions/', include('promotions_and_discounts.urls')),
    path('', include('shopping_lists.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'users.views.handle404'
handler500 = 'users.views.handle500'

categories/urls.py
from django.urls import path, include
from . import views

app_name = 'categories'
urlpatterns = [
    path('', views.categories, name='categories'),
    path('new_category/', views.new_category, name='new_category'),
    path('edit_category/<int:category_id>/', views.edit_category, name='edit_category'),
    path('<int:category_id>/', views.subcategories, name='subcategories'),
    path('<int:category_id>/delete_category/', views.delete_category, name='delete_category'),
    path('<int:subcategory_id>/delete_subcategory/', views.delete_subcategory, name='delete_subcategory'),
    path('<int:category_id>/new_subcategory/', views.new_subcategory, name='new_subcategory'),
    path('<int:subcategory_id>/edit_subcategory/', views.edit_subcategory, name='edit_subcategory'),
    path('<int:product_id>/edit_product/', views.edit_product, name='edit_product'),
    path('<int:subcategory_id>/new_product/', views.new_product, name='new_product'),
    path('<int:product_id>/delete_product/', views.delete_product, name='delete_product'),
    path('products_in_subcategory/<int:subcategory_id>', views.products_in_subcategory, name='products_in_subcategory')
]

receipts/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'receipts'
urlpatterns = [
    path('', views.your_receipts, name='your_receipts'),
    path('guarantees/', views.guarantees, name='guarantees'),
    path('new_receipt/', views.new_receipt, name='new_receipt'),
    path('new_receipt_group/<int:group_id>', views.new_receipt_group, name='new_receipt_group'),
    path('new_receipt_mainpage/', views.new_receipt_mainpage, name='new_receipt_mainpage'),
    path('new_guarantee/', views.new_guarantee, name='new_guarantee'),
    path('new_guarantee_from_mainpage/', views.new_guarantee_from_mainpage, name='new_guarantee_from_mainpage'),
    path('costs_by_hand/', views.costs_by_hand, name='costs_by_hand'),
    path('receipt_site/<int:receipt_id>', views.receipt_site, name='receipt_site'),
    path('guarantee_site/<int:guarantee_id>', views.guarantee_site, name='guarantee_site'),
    path('expense_site/<int:expense_id>', views.expense_site, name='expense_site'),
    path('expenses_page/', views.expenses_page, name='expenses_page'),
    path('receipt_by_hand/', views.receipt_by_hand, name='receipt_by_hand'),
    path('receipt_by_hand_mainpage/', views.receipt_by_hand_mainpage, name='receipt_by_hand_mainpage'),
    path('<int:group_id>/receipt_by_hand_group/', views.receipt_by_hand_group, name='receipt_by_hand_group'),
    path('receipts_page/', views.receipts_page, name='receipts_page'),
    path('receipt_settings/', views.receipt_settings, name='receipt_settings'),
    path('expense_settings/', views.expense_settings, name='expense_settings'),
    path('guarantee_settings/', views.guarantee_settings, name='guarantee_settings'),
    path('<int:expense_id>/edit_expense/', views.edit_expense, name='edit_expense'),
    path('<int:expense_id>/<int:group_id>/edit_expense_group/', views.edit_expense_group, name='edit_expense_group'),
    path('<int:expense_id>/edit_expense_mainpage/', views.edit_expense_mainpage, name='edit_expense_mainpage'),
    path('<int:guarantee_id>/edit_guarantee/', views.edit_guarantee, name='edit_guarantee'),
    path('<int:guarantee_id>/edit_guarantee_mainpage/', views.edit_guarantee_mainpage, name='edit_guarantee_mainpage'),
    path('<int:guarantee_id>/elongate_guarantee/', views.elongate_guarantee, name='elongate_guarantee'),
    path('<int:guarantee_id>/elongate_guarantee_mainpage/', views.elongate_guarantee_mainpage, name='elongate_guarantee_mainpage'),
    path('<int:receipt_id>/edit_receipt/', views.edit_receipt, name='edit_receipt'),
    path('<int:receipt_id>/edit_receipt_mainpage/', views.edit_receipt_mainpage, name='edit_receipt_mainpage'),
    path('<int:receipt_id>/<int:group_id>/edit_receipt_group/', views.edit_receipt_group, name='edit_receipt_group'),
    path('<int:receipt_id>/delete_receipt/', views.delete_receipt, name='delete_receipt'),
    path('<int:receipt_id>/<int:group_id>/delete_receipt_group/', views.delete_receipt_group, name='delete_receipt_group'),
    path('<int:receipt_id>/delete_receipt_mainpage/', views.delete_receipt_mainpage, name='delete_receipt_mainpage'),
    path('<int:expense_id>/delete_expense/', views.delete_expense, name='delete_expense'),
    path('<int:expense_id>/<int:group_id>/delete_expense_group/', views.delete_expense_group, name='delete_expense_group'),
    path('<int:expense_id>/delete_expense_mainpage/', views.delete_expense_mainpage, name='delete_expense_mainpage'),
    path('<int:group_id>/add_expense_from_grouppage/', views.add_expense_from_grouppage, name='add_expense_from_grouppage'),
    path('add_expense_from_mainpage/', views.add_expense_from_mainpage, name='add_expense_from_mainpage'),
    path('<int:guarantee_id>/delete_guarantee/', views.delete_guarantee, name='delete_guarantee'),
    path('<int:guarantee_id>/delete_guarantee_mainpage/', views.delete_guarantee_mainpage, name='delete_guarantee_mainpage'),
    path('<int:receipt_id>/OCR_site/', views.OCR_site, name='OCR_site'),
    path('<int:receipt_id>/OCR_site_mainpage/', views.OCR_site_mainpage, name='OCR_site_mainpage'),
    path('<int:receipt_id>/<int:group_id>/OCR_site_group/', views.OCR_site_group, name='OCR_site_group'),
    path('<int:receipt_id>/change_receipt_starred_status/', views.change_receipt_starred_status, name='change_receipt_starred_status'),
    path('<int:receipt_id>/change_receipt_starred_status_mainpage/', views.change_receipt_starred_status_mainpage, name='change_receipt_starred_status_mainpage'),
    path('<int:receipt_id>/<int:group_id>/change_receipt_starred_status_group/', views.change_receipt_starred_status_group, name='change_receipt_starred_status_group'),
    path('<int:expense_id>/change_expense_starred_status/', views.change_expense_starred_status, name='change_expense_starred_status'),
    path('<int:expense_id>/<int:group_id>/change_expense_starred_status_fromgroup/', views.change_expense_starred_status_fromgroup, name='change_expense_starred_status_fromgroup'),
    path('<int:expense_id>/change_expense_starred_status_mainpage/', views.change_expense_starred_status_mainpage, name='change_expense_starred_status_mainpage'),
    path('<int:receipt_id>/receipt_data_read/', views.receipt_data_read, name='receipt_data_read'),
    path('<int:receipt_id>/receipt_site_from_mainpage/', views.receipt_site_from_mainpage, name='receipt_site_from_mainpage'),
    path('<int:receipt_id>/<int:group_id>/receipt_site_from_grouppage/', views.receipt_site_from_grouppage, name='receipt_site_from_grouppage'),
    path('<int:expense_id>/expense_site_from_mainpage/', views.expense_site_from_mainpage, name='expense_site_from_mainpage'),
    path('<int:expense_id>/<int:group_id>/expense_site_from_grouppage/', views.expense_site_from_grouppage, name='expense_site_from_grouppage'),
    path('<int:guarantee_id>/guarantee_site_from_mainpage/', views.guarantee_site_from_mainpage, name='guarantee_site_from_mainpage'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register')
]

categories/views.py
from django.shortcuts import render, redirect
from .models import BaseCategories, SubCategories, Product
from .forms import NewCategoryForm, NewSubCategoryForm, NewProductForm
from groups.models import CommonGroups
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404


@login_required
def categories(request):
    base_main_categories = BaseCategories.objects.all().order_by("category_name")
    cat_public = base_main_categories.filter(owner=None)
    cat_private = base_main_categories.filter(owner=request.user)

    page_number = request.GET.get('page', 1)
    p = Paginator(cat_public, 6)

    try:
        pages_public = p.page(page_number)
    except PageNotAnInteger:
        pages_public = p.page(1)
    except EmptyPage:
        pages_public = p.page(p.num_pages)

    page_number_priv = request.GET.get('page', 1)
    p_priv = Paginator(cat_private, 6)

    try:
        pages_private = p_priv.page(page_number_priv)
    except PageNotAnInteger:
        pages_private = p_priv.page(1)
    except EmptyPage:
        pages_private = p_priv.page(p_priv.num_pages)

    context = {'main_categories': base_main_categories, "cat_public": cat_public, "cat_private":cat_private,
               'pages_public': pages_public, 'pages_private': pages_private}
    return render(request, 'categories/categories.html', context)


@login_required
def new_category(request):
    if request.method == 'POST':
        form = NewCategoryForm(data=request.POST)
        if form.is_valid():
            cat = form.save(commit=False)
            if 'public' not in request.POST:
                cat.owner = request.user
            cat.color = request.POST["color"]
            cat.save()
            messages.success(request, "Dodano nową kategorię.")
            return redirect('categories:categories')
        else:
            messages.error(request, "Coś poszło nie tak.")
    else:
        form = NewCategoryForm()
    context = {'form':form, 'user': request.user}
    return render(request, 'categories/new_category.html', context)


@login_required
def edit_category(request, category_id):
    cat = BaseCategories.objects.get(id=category_id)

    if request.user != cat.owner:
        return Http404

    if request.method == 'POST':
        form = NewCategoryForm(instance=cat, data=request.POST)
        if form.is_valid():
            cat = form.save(commit=False)
            cat.color = request.POST['color']
            cat.save()
            messages.success(request, "Kategoria została edytowana.")
            return redirect('categories:subcategories', category_id=cat.id)
        else:
            messages.error(request, "Dodano nową kategorię.")
    else:
        form = NewCategoryForm(instance=cat)
    context = {'form': form, 'category': cat}
    return render(request, 'categories/edit_category.html', context)


@login_required
def subcategories(request, category_id):
    category = get_object_or_404(BaseCategories, id=category_id)
    subcats = SubCategories.objects.filter(category=category).order_by("subcategory_name")

    page_number_priv = request.GET.get('page', 1)
    p_priv = Paginator(subcats, 10)

    try:
        pages = p_priv.page(page_number_priv)
    except PageNotAnInteger:
        pages = p_priv.page(1)
    except EmptyPage:
        pages = p_priv.page(p_priv.num_pages)

    context = {"category": category, "subcategories": subcats, "pages": pages,
               "user": request.user}

    return render(request, 'categories/sub_categories.html', context)


@login_required
def new_subcategory(request, category_id):
    category = BaseCategories.objects.get(id=category_id)
    if request.method == "POST":
        form = NewSubCategoryForm(data=request.POST)
        if form.is_valid():
            new_subcat = form.save(commit=False)
            new_subcat.owner = request.user
            new_subcat.category = category
            new_subcat.color = request.POST['color']
            new_subcat.save()
            messages.success(request, "Dodano nową podkategorię.")
            return redirect('categories:subcategories', category_id=category_id)
        else:
            print(form.errors.as_data())
            messages.error(request, "Coś poszło nie tak.")
    else:
        form = NewSubCategoryForm()
    context = {'form': form, 'category': category}
    return render(request, 'categories/new_subcategory.html', context)


@login_required
def edit_subcategory(request, subcategory_id):
    subcat = SubCategories.objects.get(id=subcategory_id)
    cat = subcat.category
    if request.user != subcat.owner:
        return Http404

    if request.method == 'POST':
        form = NewSubCategoryForm(instance=subcat, data=request.POST)
        if form.is_valid():
            new_subcat = form.save(commit=False)
            new_subcat.color = request.POST['color']
            new_subcat.save()
            messages.success(request, "Kategoria została edytowana.")
            return redirect('categories:subcategories', category_id=cat.id)
        else:
            messages.error(request, "Dodano nową kategorię.")
    else:
        form = NewSubCategoryForm(instance=subcat)
    context = {'form': form, 'subcategory': subcat, 'category': cat}
    return render(request, 'categories/edit_subcategory.html', context)


@login_required
def products_in_subcategory(request, subcategory_id):
    subcat = SubCategories.objects.get(id=subcategory_id)
    category = subcat.category
    sub_products = Product.objects.filter(subcategory=subcat)
    user = request.user
    page_number_priv = request.GET.get('page', 1)
    p_priv = Paginator(sub_products, 10)

    try:
        pages = p_priv.page(page_number_priv)
    except PageNotAnInteger:
        pages = p_priv.page(1)
    except EmptyPage:
        pages = p_priv.page(p_priv.num_pages)

    context = {"subcategory": subcat, 'category': category, 'sub_products': sub_products,
               'pages':pages, "user": user}
    return render(request, 'categories/products_in_subcategory.html', context)


@login_required
def delete_category(request, category_id):
    category = BaseCategories.objects.get(id=category_id)
    category.delete()
    return redirect("categories:categories")


@login_required
def delete_subcategory(request, subcategory_id):
    subcategory = get_object_or_404(SubCategories, id=subcategory_id)
    category = subcategory.category
    subcategory.delete()
    return redirect("categories:subcategories", category_id=category.id)


@login_required
def delete_product(request, product_id):
    prod = get_object_or_404(Product, id=product_id)
    subcat = prod.subcategory
    prod.delete()
    return redirect("categories:products_in_subcategory", subcategory_id=subcat.id)


@login_required
def new_product(request, subcategory_id):
    subcat = get_object_or_404(SubCategories, id=subcategory_id)
    cat = subcat.category
    if request.method == "POST":
        form = NewProductForm(data=request.POST)
        if form.is_valid():
            new_prod = form.save(commit=False)
            new_prod.subcategory = subcat
            new_prod.save()
            messages.success(request, "Poprawnie dodano produkt do kategorii.")
            return redirect('categories:products_in_subcategory', subcategory_id=subcategory_id)
        else:
            messages.error(request, "Coś poszło nie tak.")
    else:
        form = NewProductForm()

    context = {'subcategory': subcat, 'category': cat,'form': form}
    return render(request,"categories/new_product.html", context)


@login_required
def edit_product(request, product_id):
    prod = get_object_or_404(Product, id=product_id)
    subcat = prod.subcategory
    category = prod.subcategory.category
    if request.method == "POST":
        form = NewProductForm(instance=prod, data=request.POST)
        if form.is_valid():
            new_prod = form.save(commit=False)
            new_prod.save()
            messages.success(request, "Poprawnie dodano produkt do kategorii.")
            return redirect('categories:products_in_subcategory', subcategory_id=subcat.id)
        else:
            messages.error(request, "Coś poszło nie tak.")
    else:
        form = NewProductForm(instance=prod)

    context = {'form': form, "prod": prod,'subcategory': subcat, 'category': category}
    return render(request, "categories/edit_product.html", context)

categories/templates/categories/sub_categories.html
{% extends "shopping_lists/base.html" %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <style>
        h2{
            text-align: center;
        }

        .color_block{

            border-radius: 10px;
            margin: 10px;
            padding: 15px;
            transition: 0.5s;
            width: 300px;
            cursor: pointer;
        }

        .color_block_noclick{
            width: 150px;
            height: 90%;
            border-radius: 10px;
            margin: 10px;
            padding: 15px;
            display: flex;
            align-items: center;
        }

        .color_block:hover{
            filter: brightness(85%);
            transition: 0.5s;
        }

    </style>

    <div>
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                     <div id="messages" class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% else %}
                     <div id="messages" class="alert alert-danger">
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}

        <script>
            var mess = document.getElementById("messages")

            setTimeout(function(){
                mess.style.display="none";
            },2000)
        </script>
    </div>


    <a href="{% url 'categories:categories' %}">
        <div style="position: absolute; margin-top: 15px;color: black; margin-left: 15px">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
            </svg>
        </div>
    </a>

    <h1 style="margin-top: 20px">{{ category }}</h1>

    <div style="margin: auto">
        {% for subcat in pages %}
            <a style="text-decoration: none; color: black" href="{% url 'categories:products_in_subcategory' subcat.id %} " >

                <div class="color_block" style="background-color: {{ subcat.color }};">
                    <span style="margin: auto;">{{ subcat }}</span>
                </div>
            </a>
        {% empty %}
            <div class="color_block_noclick" style=" width:280px;background-color: lightgray; margin: auto">
                <span style="margin: auto">Brak podkategorii</span>
            </div>
        {% endfor %}
    </div>

        <div style="text-align: center; margin: 10px auto">
        {% if pages.has_other_pages %}
          <ul class="pagination">
            {% if pages.has_previous %}
              <li><a style="text-decoration: none; color: black" href="?page={{ pages.previous_page_number }}">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
                </svg>
              </a></li>
            {% else %}
              <li class="disabled"><span>
                <svg xmlns="http://www.w3.org/2000/svg" color="lightgray" width="32" height="32" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
                </svg>
              </span></li>
            {% endif %}

              <li class="active" style="margin:0 20px"><span>{{ pages.number }}/{{ pages.paginator.num_pages }} <span class="sr-only"></span></span></li>

            {% if pages.has_next %}
              <li><a style="text-decoration: none; color: black" href="?page={{ pages.next_page_number }}">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
                </svg>
              </a></li>
            {% else %}
              <li class="disabled"><span>
                <svg xmlns="http://www.w3.org/2000/svg" color="lightgray" width="32" height="32" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
                </svg>
              </span></li>
            {% endif %}
          </ul>
        {% endif %}
    </div>

    {% if user == category.owner %}
    <div id="icons_container_id" style="margin: 10px auto">
        <a href="{% url 'categories:edit_category' category.id %}" style="text-decoration: none; color: black;margin-right: 25px">
            <div style="display: inline;">
                <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                </svg>
            </div>
            <span style="margin-left: 10px">Edytuj kategorię</span>
        </a>
    </div>

    <div id="icons_container_id" style="margin: 10px auto">
        <a href="{% url 'categories:new_subcategory' category.id %}" style="text-decoration: none; color: black;">
            <div style="display: inline;">
                <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-patch-plus" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M8 5.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V10a.5.5 0 0 1-1 0V8.5H6a.5.5 0 0 1 0-1h1.5V6a.5.5 0 0 1 .5-.5z"/>
                  <path d="m10.273 2.513-.921-.944.715-.698.622.637.89-.011a2.89 2.89 0 0 1 2.924 2.924l-.01.89.636.622a2.89 2.89 0 0 1 0 4.134l-.637.622.011.89a2.89 2.89 0 0 1-2.924 2.924l-.89-.01-.622.636a2.89 2.89 0 0 1-4.134 0l-.622-.637-.89.011a2.89 2.89 0 0 1-2.924-2.924l.01-.89-.636-.622a2.89 2.89 0 0 1 0-4.134l.637-.622-.011-.89a2.89 2.89 0 0 1 2.924-2.924l.89.01.622-.636a2.89 2.89 0 0 1 4.134 0l-.715.698a1.89 1.89 0 0 0-2.704 0l-.92.944-1.32-.016a1.89 1.89 0 0 0-1.911 1.912l.016 1.318-.944.921a1.89 1.89 0 0 0 0 2.704l.944.92-.016 1.32a1.89 1.89 0 0 0 1.912 1.911l1.318-.016.921.944a1.89 1.89 0 0 0 2.704 0l.92-.944 1.32.016a1.89 1.89 0 0 0 1.911-1.912l-.016-1.318.944-.921a1.89 1.89 0 0 0 0-2.704l-.944-.92.016-1.32a1.89 1.89 0 0 0-1.912-1.911l-1.318.016z"/>
                </svg>
            </div>
            <span style="margin-left: 10px">Dodaj podkategorię</span>
        </a>
    </div>


        <div id="icons_container_id" style="margin: 10px auto">
            <a href="{% url 'categories:delete_category' category.id %}" style="text-decoration: none; color: black;margin-right: 35px">
                <div style="display: inline; ">
                    <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                      <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                      <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                    </svg>
                </div>
                <span style="margin-left: 10px">Usuń kategorię</span>
            </a>
        </div>
    {% endif %}

{% endblock content %}